Repository banzaicloud/koperator, pull requests merged in 2019-09, with the labels that each got.

#120 fix conversion in case of crd
  charts/kafka-operator/templates/operator-kafka-topic-crd.yaml
  config/crd/bases/banzaicloud.banzaicloud.io_kafkaclusters.yaml
  config/crd/bases/banzaicloud.banzaicloud.io_kafkatopics.yaml
  config/crd/bases/banzaicloud.banzaicloud.io_kafkausers.yaml
  config/crd/patches/webhook_in_kafkatopics.yaml
Labels: bug

#126 Stop extra reconcile attempts on clusterissuers and bootstrap secret
  pkg/resources/pki/certs.go
  pkg/resources/pki/pki.go
Labels: community

#132 Fix Storage Config
  pkg/resources/kafka/configmap.go
  pkg/resources/kafka/configmap_test.go
Labels: bug, community

#150 Prune/imagePullSecrets
  charts/kafka-operator/Chart.yaml
  charts/kafka-operator/templates/authproxy-rbac.yaml
  charts/kafka-operator/templates/operator-deployment.yaml
  charts/kafka-operator/templates/operator-rbac.yaml
  charts/kafka-operator/values.yaml
Labels: community, enhancement
