Repository banzaicloud/koperator, pull requests merged in 2019-10, with the labels that each got.

#159 Renaming the directory eks-istio-mtls-on:off to eks-istio-mtls-on-off
  docs/benchmarks/results/eks-istio-mtls-on-off/1broker-2.png
  docs/benchmarks/results/eks-istio-mtls-on-off/1broker-mtls-off.png
  docs/benchmarks/results/eks-istio-mtls-on-off/1broker-mtls-on.png
  docs/benchmarks/results/eks-istio-mtls-on-off/1broker.png
  docs/benchmarks/results/eks-istio-mtls-on-off/1client.png
  docs/benchmarks/results/eks-istio-mtls-on-off/2broker-2.png
  docs/benchmarks/results/eks-istio-mtls-on-off/2broker-mtls-off.png
  docs/benchmarks/results/eks-istio-mtls-on-off/2broker-mtls-on.png
  docs/benchmarks/results/eks-istio-mtls-on-off/2broker.png
  docs/benchmarks/results/eks-istio-mtls-on-off/2client.png
  docs/benchmarks/results/eks-istio-mtls-on-off/3broker-3.png
  docs/benchmarks/results/eks-istio-mtls-on-off/3broker-mtls-off.png
  docs/benchmarks/results/eks-istio-mtls-on-off/3broker-mtls-on.png
  docs/benchmarks/results/eks-istio-mtls-on-off/3broker.png
Labels: community

#162 fix port int convertation
  pkg/util/util.go
  pkg/util/util_test.go
Labels: bug, community

#163 Alert/pre filtering
  README.md
  internal/alertmanager/dispatcher/dispatcher.go
  internal/alertmanager/dispatcher/dispatcher_test.go
Labels: enhancement

#168 Add the ability to set annotations on the broker pods
  api/v1beta1/kafkacluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kafka.banzaicloud.io_kafkaclusters.yaml
  pkg/resources/kafka/pod.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: community, enhancement

#178 Fix directory reference typo in README
  README.md
Labels: community, documentation
